version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      -"/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
